# DO NOT EDIT THIS FILE.
# It is automatically synchronized with golang-libraries.

include Makefile-common.mk

.DEFAULT_GOAL=build

PROJECT?=$(shell basename $(shell pwd))

GO_BUILD_DIR=build
.PHONY: build
build:: install-dependencies
	mkdir -p $(GO_BUILD_DIR)
	go build -v -ldflags="-s -w -X main.version=$(VERSION)" -o $(GO_BUILD_DIR) ./cmd/...

.PHONY: lint-rules
lint-rules::
	# Mandatory files.
	[ -e .dockerignore ]
	[ -e Dockerfile ]

.PHONY: mod-update-golang-libraries
mod-update-golang-libraries:
	go get -v -u -d github.com/siddhant2408/golang-libraries@latest
	$(MAKE) mod-tidy

.PHONY: mod-edit-replace-golang-libraries-local
mod-edit-replace-golang-libraries-local:
	go mod edit -replace=github.com/siddhant2408/golang-libraries=../golang-libraries

.PHONY: mod-edit-dropreplace-golang-libraries
mod-edit-dropreplace-golang-libraries:
	go mod edit -dropreplace=github.com/siddhant2408/golang-libraries

ifeq ($(CI),true)

ci::
	$(call CI_LOG_GROUP_START,build)
	$(MAKE) build
	$(call CI_LOG_GROUP_END)

	$(call CI_LOG_GROUP_START,test)
	$(MAKE) test
	$(call CI_LOG_GROUP_END)

	$(call CI_LOG_GROUP_START,lint)
	$(MAKE) lint
	$(call CI_LOG_GROUP_END)

endif # CI end
